---
- hosts: all
  become_user: root
  become: true
  tasks:
   - name: Installing packages
     dnf: name={{item}} state=present
     with_items:
      - git
      - zathura-pdf-mupdf
      - zathura
      - zsh
      - zsh-syntax-highlighting
      - w3m
      - udiskie
      - tlp
      - xorg-x11-drv-synaptics-devel
      - xorg-x11-drv-synaptics
      - transmission
      - stardict
      - stardict-dic-cs_CZ
      - rxvt-unicode-256color
      - ranger
      - powertop
      - nmap
      - newsbeuter
      - network-manager-applet
      - nano
      - links
      - irssi
      - i3status
      - i3
      - i3lock
      - feh
      - elinks
      - dmenu
      - chromium
      - mercurial
      - pavucontrol
      - xbacklight

   - name: Installing Oh-my-zsh
     shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

#   - name: Changing shell to ZSH
#     shell: su - john -c "chsh -s /usr/bin/zsh"
