---
- hosts: all
  become_user: root
  become: true
  tasks:
   - name: Installing packages
     dnf: name={{item}} state=present
     with_items:
      - git
      - zathura-pdf-mupdf
      - zathura
      - zsh
      - zsh-syntax-highlighting
      - w3m
      - udiskie
      - tlp
      - xorg-x11-drv-synaptics-devel
      - xorg-x11-drv-synaptics
      - transmission
      - stardict
      - stardict-dic-cs_CZ
      - rxvt-unicode-256color
      - ranger
      - powertop
      - nmap
      - newsbeuter
      - network-manager-applet
      - nano
      - links
      - irssi
      - i3status
      - i3
      - i3lock
      - feh
      - elinks
      - dmenu
      - chromium
      - mercurial
      - pavucontrol
      - xbacklight
      - fortune-mod

#   - name: Downloading oh-my-zsh
#     shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
   
#   - name: Downloading zsh-completion
#     shell: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions

#   - name: Downloading zsh-syntax-highlighting
#     shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

#   - name: Changing shell to ZSH
#     shell: chsh -s /usr/bin/zsh

   - name: disable gdm
     shell: systemctl disable gdm.service

