- name: Create directory for personal projecs
  ansible.builtin.file:
    path: "{{ personal_projects }}"
    state: directory
    mode: "0755"
  tags:
  - essentials
  ignore_errors: true
  when: username == "john" #Create only for john user
