---
- hosts: all
  become_user: root
  become: true
  vars:
     ansible_python_interpreter: python3
  tasks:
  
   - name: check fedora version
     shell: rpm -E %fedora
     register: current_fedora

   - name: Setting up ffmpeg
     dnf: name={{item}} state=present
     with_items:
       - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ current_fedora.stdout }}.noarch.rpm"
       - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ current_fedora.stdout }}.noarch.rpm"


   - name: Installing packages
     dnf: name={{item}} state=present
     with_items:
      - git
      - zathura-pdf-mupdf
      - zathura
      - zsh
      - nano
      - zsh-syntax-highlighting
      - w3m
      - udiskie
      - tlp
      - xorg-x11-drv-synaptics-devel
      - xorg-x11-drv-synaptics
      - transmission
      - stardict
      - stardict-dic-cs_CZ
      - rxvt-unicode-256color
      - ranger
      - powertop
      - nmap
      - newsbeuter
      - network-manager-applet
      - nano
      - links
      - irssi
      - i3status
      - i3
      - i3lock
      - feh
      - elinks
      - dmenu
      - chromium
      - mercurial
      - pavucontrol
      - xbacklight
      - fortune-mod
      - vim
      - xterm
      - brasero
      - pip
      - lm_sensors
      - compton
      - shutter
      - conky
      - numlockx
      - telegram-desktop
      - pcmanfm
      - unrar
      - ffmpeg
      - ffmpeg-devel
      - vlc

   - name: add sublime_text rpm
     shell: rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg

   - name: Add Sublime Text repo
     shell:  'dnf config-manager \
       --add-repo \
       https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo'

   - name: Install Sublime Text
     dnf:
       name: sublime-text
       state: latest

#   - name: Downloading oh-my-zsh
#     shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
   
#   - name: Downloading zsh-completion
#     shell: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions

#   - name: Downloading zsh-syntax-highlighting
#     shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

#   - name: Changing shell to ZSH
#     shell: chsh -s /usr/bin/zsh

   - name: disable gdm
     shell: systemctl disable gdm.service

   - name: Downloading and compiling fortunes-fr
     shell: wget https://www.fortunes-fr.org/fortunes-fr/fortunes-fr-0.02.tar.gz -O ~/fortunes-fr.tar.gz
   - name: Extracting fortunes-fr
     shell: tar -zxvf ~/fortunes-fr.tar.gz -C ~/
   - name: Install fortunes-fr
     shell: cd ~/fortunes-fr-0.02; ./configure; make; make install
   - name: Clean fortunes-fr
     shell: rm -rf ~/fortunes-fr-0.02; rm -rf ~/fortunes-fr.tar.gz

   - name: Setup youtube-dl
     shell: wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl && chmod a+x /usr/local/bin/youtube-dl

   - pip:
       name:
         - bottle
         - jsmin 
         - pyowm
         - bs4
         - lxml
         - requests
