---
- hosts: all
  become_user: root
  become: true
  vars:
     ansible_python_interpreter: python3
  tasks:
  
   - name: Installing tex packages
     dnf: name={{item}} state=present
     with_items:
      - texmaker
      - texlive-pdfcprot
      - texlive-acronym
      - texlive-babel-czech
      - texlive-titling
      - texlive-collection-langcyrillic
      - texlive-cyrillic
      - texlive-babel-russian
      - texlive-babel-german
      - texlive-babel-french

