---
- hosts: all
  become_user: root
  become: true
  vars:
     ansible_python_interpreter: python3
  tasks:
  
   - name: check fedora version
     shell: rpm -E %fedora
     register: current_fedora
     args:
       warn: false

   - name: Setting up ffmpeg
     dnf: name={{item}} state=present validate_certs=no disable_gpg_check=yes
     loop:
       - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ current_fedora.stdout }}.noarch.rpm"
       - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ current_fedora.stdout }}.noarch.rpm"
     become: true


   - name: Installing packages
     #ignore_errors: true
     dnf:
       name: "{{ item }}"
       state: present
       update_cache: true
     with_items:
      - git
      - zathura-pdf-mupdf
      - zathura
      - make
      - zsh
      - nano
      - zsh-syntax-highlighting
      - w3m
      - udiskie
      - redshift
      - tlp
      - xorg-x11-drv-synaptics-devel
      - xorg-x11-drv-synaptics
      - transmission
      - stardict
      - stardict-dic-cs_CZ
      - ranger
      - powertop
      - nmap
      - newsbeuter
      - network-manager-applet
      - nano
      - links
      - irssi
      - i3status
      - i3
      - i3lock
      - feh
      - elinks
      - dmenu
      - chromium
      - mercurial
      - pavucontrol
      - xbacklight
      - fortune-mod
      - vim
      - vifm
      - xterm
      - brasero
      - pip
      - lm_sensors
      - compton
      - shutter
      - conky
      - numlockx
      - telegram-desktop
      - pcmanfm
      - unrar
      - ffmpeg
      - ffmpeg-devel
      - vlc
      - java-11-openjdk
      - audacity
      # TeamViewer dependencies
      - qt5-qtquickcontrols
      - qt5-qtlocation
      - qt5-qtsensors
      - qt5-qtwebchannel
      - qt5-qtwebkit
     become: true


   - name: Add Sublime Text rpm
     shell: 'rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg'
     args:
       warn: false

   - name: Add Sublime Text repo
     shell:  'dnf config-manager \
       --add-repo \
       https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo'

   - name: Install Sublime Text
     dnf:
       name: sublime-text
       state: latest

#   - name: Downloading oh-my-zsh
#     shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
   
#   - name: Downloading zsh-completion
#     shell: git clone https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions

#   - name: Downloading zsh-syntax-highlighting
#     shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

#   - name: Changing shell to ZSH
#     shell: chsh -s /usr/bin/zsh

   - name: Disable gdm
     shell: systemctl disable gdm.service


   - name: Download and unpack fortunes-fr
     unarchive:
       src: https://www.fortunes-fr.org/fortunes-fr/fortunes-fr-0.02.tar.gz
       dest: ~/
       remote_src: yes

   - name: Install fortunes-fr
     shell: 'cd ~/fortunes-fr-0.02; ./configure; make; make install'
   #- name: Clean fortunes-fr
   #  shell: 'rm -rf ~/fortunes-fr-0.02; rm -rf ~/fortunes-fr.tar.gz'
   - name: Clean fortunes-fr
     file:
       path: ~/fortunes-fr-0.02
       state: absent

   - name: Download youtube-dl
     get_url:
       url: https://yt-dl.org/latest/youtube-dl
       dest: /usr/local/bin/youtube-dl

   - name: chmod youtube-dl
     file:
       path: /usr/local/bin/youtube-dl
       state: file
       mode: u+rwx,g+rx,o+rx

   - name: Install pip modules
     pip:
       name:
         - bottle
         - jsmin 
         - pyowm
         - bs4
         - lxml
         - requests

