# vim:ft=zsh:
#
# Final init script executed on login shell - in essence late .zprofile

### Print fortune [french law related] on login shell
[ -x /usr/bin/fortune ] && fortune droit

### start X on tty1 + fix sound bug on some machines
if [[ "$(tty)" == '/dev/tty1' ]]; then
	$(amixer -D pulse sset Master on)
	$(startx i3)
fi

