# vim:ft=zsh:
#
# Final init script executed on login shell - in essence late .zprofile

export ZLOGIN=true

### Print fortune [french law related] on login shell
[ -x /usr/bin/fortune ] && fortune /usr/local/share/games/fortunes

### start X on tty1 + fix sound bug on some machines
if [[ "$(tty)" == '/dev/tty1' ]]; then
	$(startx i3)
	# > /dev/null 2>&1 = no output on the screen
	$(amixer -D pulse sset Master on) > /dev/null 2>&1
fi


