#!/bin/bash

# .zlogin does not get called from BASH, and .profile does not get called from ZSH
# For this reason we ensure reciprocity. BASH is our default shell, so we call .profile also when zsh is in action.

# Do not do it for root
if [[ "$EUID" -ne 0 ]]; then
    source ~/.profile
fi

